# 6.5 The workhorse equations (with shapes)
## 6.5A Linear regression (batch prediction)

In [12]:
import numpy as np

# Example pattern (yours may differ!)
rng = np.random.default_rng(0)
mean = np.array([1.0, -1.0])
cov = np.array([[1.5, 0.8],
                [0.8, 1.0]])
X = rng.multivariate_normal(mean, cov, size=120)

In [20]:
w = np.array([0.8, -0.3])   # n=3
b = 0.2
y_hat = X @ w + b 

In [22]:
print(f"w: {w}")
print(f"b: {b}")
print(f"Y Pred: {y_hat}")

w: [ 0.8 -0.3]
b: 0.2
Y Pred: [ 1.27584538  0.8197847   1.49532098 -0.01462792  2.35586599  1.70149631
  2.96898936  2.47679233  1.81242112  0.54355868  0.75920008  1.58733276
  0.64732719  2.22485831  1.50767278  2.07716818  1.15904757  0.9919909
  1.80060828  0.08529485  1.45416295  0.03324734  1.26575335 -0.58380836
 -0.51934765  1.6137919   1.00153614  1.98770664  0.69036566  2.40270047
  2.131629    0.35431939  1.1968127  -0.37458518  1.88463039  0.95093539
  0.90646366  0.67720541  1.31688391  0.347361    1.46359856  2.05579228
  1.87245038  0.31344139  1.03339525  0.77087257  1.92971772  0.657822
  1.46026812  2.84842628  0.50638001  1.9042102   1.29901422  1.49586488
  2.64056297  1.64220344  1.25825418  1.17995809  0.00793606  0.19586714
  0.38105552  1.90421102  1.74448349  2.14112419  2.15646592  1.88036723
  0.45072875  0.83094984 -0.17418068  2.33144376  0.87627938  0.87379103
  1.24933781  2.63289972  1.34617814  1.45647417  2.10765204  1.98989963
  1.14586231  3.20123661

## 6.5B Cosine Similarity (Rows normalized)

In [26]:
X_norm = X / np.linalg.norm(X, axis=1, keepdims=True)  # (m,n)
S = X_norm @ X_norm.T                                  # (m,m) similarities
S

array([[ 1.        ,  0.87142359,  0.77674405, ...,  0.74283295,
         0.60583486,  0.43215309],
       [ 0.87142359,  1.        ,  0.36792845, ...,  0.31892284,
         0.13767679, -0.06577284],
       [ 0.77674405,  0.36792845,  1.        , ...,  0.99863854,
         0.97165451,  0.90364092],
       ...,
       [ 0.74283295,  0.31892284,  0.99863854, ...,  1.        ,
         0.98266344,  0.92475192],
       [ 0.60583486,  0.13767679,  0.97165451, ...,  0.98266344,
         1.        ,  0.97927706],
       [ 0.43215309, -0.06577284,  0.90364092, ...,  0.92475192,
         0.97927706,  1.        ]])

# 6.6 Centering & scaling
## 6.6A Centering (remove mean per feature)

In [31]:
mu = X.mean(axis=0, keepdims=True)  # (1,n)
Xc = X - mu
print(Xc)

[[-2.23608908e-01 -3.46037539e-01]
 [-9.12937650e-01 -6.64045228e-01]
 [ 3.58759236e-01  4.75358860e-01]
 [-2.00565485e+00 -7.96582368e-01]
 [ 1.17291547e+00 -2.22041214e-01]
 [ 5.82499346e-01  3.84748033e-01]
 [ 2.66266340e+00  1.70687538e+00]
 [ 1.60147830e+00  5.17705194e-01]
 [ 6.26450698e-01  1.32202290e-01]
 [-1.00298301e+00  1.65872155e-02]
 [-4.97235404e-01  6.46442813e-01]
 [ 5.13393834e-01  5.81011863e-01]
 [-1.21505419e+00 -8.94830989e-01]
 [ 1.08856054e+00 -1.02954494e-02]
 [ 3.21763690e-01  3.35531403e-01]
 [ 1.12752750e+00  5.85916873e-01]
 [-1.47658574e-01  2.45822727e-01]
 [-5.12451891e-01 -1.70103902e-01]
 [ 6.83052214e-01  3.22515807e-01]
 [-1.60789795e+00 -6.89731903e-02]
 [ 7.62940298e-01  1.69036845e+00]
 [-1.99139400e+00 -9.18137620e-01]
 [-3.16006005e-01 -5.58789701e-01]
 [-2.57011775e+00 -4.04548645e-01]
 [-2.72492844e+00 -1.03224619e+00]
 [-8.42043364e-02 -1.10078040e+00]
 [-3.71806541e-01  1.73132918e-01]
 [ 1.22234277e+00  1.13696275e+00]
 [-8.92505892e-01 -1

## 6.6B Standardizing (unit variance per feature)

In [34]:
sigma = X.std(axis=0, keepdims=True) + 1e-8
Z = (X - mu) / sigma
print(Z)

[[-1.77415722e-01 -3.74200456e-01]
 [-7.24342755e-01 -7.18089801e-01]
 [ 2.84646661e-01  5.14046837e-01]
 [-1.59132616e+00 -8.61413725e-01]
 [ 9.30614292e-01 -2.40112457e-01]
 [ 4.62166481e-01  4.16061477e-01]
 [ 2.11260971e+00  1.84579265e+00]
 [ 1.27064450e+00  5.59839607e-01]
 [ 4.97038352e-01  1.42961823e-01]
 [-7.95786521e-01  1.79371973e-02]
 [-3.94516386e-01  6.99054780e-01]
 [ 4.07336803e-01  6.28298608e-01]
 [-9.64047982e-01 -9.67658496e-01]
 [ 8.63685424e-01 -1.11333640e-02]
 [ 2.55293664e-01  3.62839259e-01]
 [ 8.94602577e-01  6.33602822e-01]
 [-1.17155228e-01  2.65829473e-01]
 [-4.06589448e-01 -1.83948129e-01]
 [ 5.41947112e-01  3.48764364e-01]
 [-1.27573797e+00 -7.45867034e-02]
 [ 6.05331895e-01  1.82794227e+00]
 [-1.58001131e+00 -9.92861981e-01]
 [-2.50725403e-01 -6.04267854e-01]
 [-2.03918216e+00 -4.37473599e-01]
 [-2.16201202e+00 -1.11625749e+00]
 [-6.68093829e-02 -1.19036949e+00]
 [-2.94998650e-01  1.87223666e-01]
 [ 9.69830889e-01  1.22949660e+00]
 [-7.08131796e-01 -1

# 6.8 Tiny end-to-end demo (fit a line/plane just to see shapes)

In [41]:
# closed-form w for least squares on 2 features (no reg), centered X
# y target is synthetic
y_target = 0.7*X[:,0] - 0.2*X[:,1] + rng.normal(0,0.3, size=X.shape[0])

# Normal equation: w = (X^T X)^{-1} X^T y  (add small ridge for stability)
lam = 1e-6
XT_X = X.T @ X + lam*np.eye(X.shape[1])
w_hat = np.linalg.solve(XT_X, X.T @ y_target)
b_hat = 0.0  # skip intercept here; or add a bias column of 1s

print("w_hat:", w_hat)

w_hat: [ 0.67247723 -0.2424458 ]


---