# 7.4 Covariance

In [5]:
import numpy as np
import plotly.express as px
import plotly.graph_objects as go

# reproducibility
rng = np.random.default_rng(7)

# Two classes in 2D
m_per = 60
class0 = rng.normal(loc=[-2, -1], scale=[0.9, 0.7], size=(m_per, 2))
class1 = rng.normal(loc=[ 1.5,  1.0], scale=[0.8, 1.1], size=(m_per, 2))
X2d = np.vstack([class0, class1])
y   = np.hstack([np.zeros(m_per), np.ones(m_per)])

# Lift to 3D by adding a third feature with correlation + noise
f3 = 0.6*X2d[:,0] - 0.3*X2d[:,1] + rng.normal(0, 0.6, size=X2d.shape[0])
X3d = np.c_[X2d, f3]

mu = X3d.mean(axis=0, keepdims=True)
Xc = X3d - mu
m = Xc.shape[0]

# covariance matrix
Sigma = (Xc.T @ Xc) / (m - 1)
print("Covariance matrix:\n", Sigma)

Covariance matrix:
 [[3.84743912 1.7037686  1.979648  ]
 [1.7037686  1.52718519 0.64221164]
 [1.979648   0.64221164 1.39921855]]


# 7.9 Covariance vs Correlation

In [12]:
corr = np.corrcoef(X3d.T)
print("Correlation martix:\n",corr)

Correlation martix:
 [[1.         0.70287627 0.85321665]
 [0.70287627 1.         0.43932867]
 [0.85321665 0.43932867 1.        ]]


---